name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - archspec=0.2.3
  - blas=2.122
  - blas-devel=3.9.0
  - boltons=23.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.5.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - cycler=0.12.1
  - distro=1.8.0
  - expat=2.5.0
  - fmt=9.1.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.4
  - icu=73.1
  - idna=3.4
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsolv=0.7.24
  - libsqlite=3.45.3
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.4.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=18.1.5
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - menuinst=2.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - openblas=0.3.27
  - openjpeg=2.5.0
  - openssl=3.3.1
  - packaging=23.1
  - pcre2=10.42
  - pillow=10.3.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python.app=3
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.13
  - tornado=6.4
  - tqdm=4.65.0
  - truststore=0.8.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - anyio==4.4.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - comm==0.2.2
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - ipykernel==6.29.5
      - ipython==8.26.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook-shim==0.2.4
      - numpy==2.0.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.18.0
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12.1
      - terminado==0.18.1
      - timm==1.0.7
      - tinycss2==1.3.0
      - torch==2.3.1
      - torchvision==0.18.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
